# Generated by Django 5.2.11 on 2026-02-13 10:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license_type', models.CharField(choices=[('foundation', 'Foundation'), ('enterprise', 'Enterprise')], default='foundation', max_length=20)),
                ('foundation_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('enterprise_upgrade_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Liaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_channels', models.CharField(choices=[('email', 'Email Only'), ('email_sms', 'Email + SMS'), ('slack', 'Slack / Teams Webhook')], default='email', max_length=50)),
                ('incident_types', models.TextField(help_text='Key incident types of concern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liaison_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Low - Informational'), ('Medium', 'Medium - Potential Impact'), ('High', 'High - Critical Incident')], default='Low', max_length=10)),
                ('impact', models.TextField(blank=True, help_text='Why it matters - operational impact analysis')),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_synthesized', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_updates', to='core.liaison')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=255)),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_decisions', to='core.liaison')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShiftPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('executive_summary', models.TextField()),
                ('key_risks', models.TextField()),
                ('next_actions', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_packets', to='core.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence_hours', models.IntegerField(default=24, help_text='Shift packet cadence in hours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('distribution_list', models.TextField(blank=True, help_text='Comma-separated email addresses for shift packet distribution')),
                ('current_status', models.CharField(choices=[('Normal', 'Normal'), ('Emergency Watch', 'Emergency Watch'), ('High Alert', 'High Alert')], default='Normal', max_length=20)),
                ('current_phase', models.IntegerField(choices=[(0, 'Standard Operations'), (1, 'Escalation Protocol')], default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.organization')),
            ],
        ),
    ]
