# Generated by Django 5.2.11 on 2026-02-17 12:26

import django.db.models.deletion
from django.db import migrations, models, connection


def check_table_exists(table_name):
    """Check if a table exists in the database"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = %s
        """, [table_name])
        return cursor.fetchone()[0] > 0


def create_payment_if_not_exists(apps, schema_editor):
    """Create Payment table only if it doesn't exist"""
    if not check_table_exists('core_payment'):
        # Table doesn't exist, create it using raw SQL
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE `core_payment` (
                    `id` INT AUTO_INCREMENT PRIMARY KEY,
                    `amount` DECIMAL(10, 2) NOT NULL,
                    `payment_method` VARCHAR(20) NOT NULL DEFAULT 'INVOICE',
                    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                    `invoice_id` VARCHAR(100) NULL UNIQUE,
                    `created_at` DATETIME(6) NOT NULL,
                    `updated_at` DATETIME(6) NOT NULL,
                    `card_last4` VARCHAR(4) NULL,
                    `card_token` VARCHAR(255) NULL,
                    `organization_id` BIGINT NULL,
                    INDEX `idx_organization` (`organization_id`),
                    INDEX `idx_created_at` (`created_at`),
                    FOREIGN KEY (`organization_id`) REFERENCES `core_organization`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)


def create_invoice_if_not_exists(apps, schema_editor):
    """Create Invoice table only if it doesn't exist"""
    if not check_table_exists('core_invoice'):
        # Table doesn't exist, create it using raw SQL
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE `core_invoice` (
                    `invoice_id` VARCHAR(100) PRIMARY KEY,
                    `billing_entity_name` VARCHAR(255) NOT NULL,
                    `billing_email` VARCHAR(254) NOT NULL,
                    `po_number` VARCHAR(100) NULL,
                    `payment_terms` VARCHAR(20) NOT NULL DEFAULT 'NET_30',
                    `early_pay_terms` VARCHAR(50) NOT NULL DEFAULT '2% / 10, Net 30',
                    `due_date` DATE NOT NULL,
                    `created_at` DATETIME(6) NOT NULL,
                    `payment_id` INT NOT NULL UNIQUE,
                    FOREIGN KEY (`payment_id`) REFERENCES `core_payment`(`id`) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_payment_if_not_exists, migrations.RunPython.noop),
        migrations.RunPython(create_invoice_if_not_exists, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalSubscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('subscription_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
                ('subscription_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=150)),
                ('primary_liaison_name', models.CharField(max_length=100)),
                ('liaison_email', models.CharField(max_length=150)),
                ('key_incident_types', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_communication_channels', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_credentials',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Skip creating tables if they exist - handled by RunPython above
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Payment',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('payment_method', models.CharField(choices=[('INVOICE', 'Invoice - Net 30'), ('ACH', 'ACH (Bank Transfer)'), ('CARD', 'Credit Card')], default='INVOICE', max_length=20)),
                        ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('INVOICED', 'Invoiced'), ('PROCESSING', 'Processing')], default='PENDING', max_length=20)),
                        ('invoice_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('card_last4', models.CharField(blank=True, max_length=4)),
                        ('card_token', models.CharField(blank=True, max_length=255)),
                        ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.organization')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Invoice',
                    fields=[
                        ('invoice_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                        ('billing_entity_name', models.CharField(max_length=255)),
                        ('billing_email', models.EmailField(max_length=254)),
                        ('po_number', models.CharField(blank=True, max_length=100)),
                        ('payment_terms', models.CharField(choices=[('NET_30', 'Net 30')], default='NET_30', max_length=20)),
                        ('early_pay_terms', models.CharField(default='2% / 10, Net 30', max_length=50)),
                        ('due_date', models.DateField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.payment')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stripepayments',
                'managed': False,  # Table already exists
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_payment_intent_id'], name='stripepayme_stripe__a97cae_idx'), models.Index(fields=['status'], name='stripepayme_status_a932bb_idx'), models.Index(fields=['user_id'], name='stripepayme_user_id_a27b03_idx')],
            },
        ),
    ]
