# Generated by Django 5.2.11 on 2026-02-17 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_externalpayment_externalsubscription_externaluser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=255)),
                ('subscription_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelTable(
            name='organization',
            table='core_organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this organization belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='core.tenant'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_title', models.CharField(db_column='update_title', max_length=255)),
                ('severity', models.CharField(choices=[('Low', 'Low - Informational'), ('Medium', 'Medium - Potential Impact'), ('High', 'High - Critical Incident')], default='Low', max_length=50)),
                ('owner_name', models.CharField(db_column='owner_name', max_length=255)),
                ('what_changed', models.TextField(db_column='what_changed')),
                ('impact', models.TextField()),
                ('next_action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('tenant', models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.tenant')),
            ],
            options={
                'db_table': 'core_incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='core_incide_tenant__2db550_idx'), models.Index(fields=['created_at'], name='core_incide_created_3c0b22_idx'), models.Index(fields=['severity'], name='core_incide_severit_a2f6c2_idx')],
            },
        ),
    ]
