# Generated by Django 5.2.11 on 2026-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_alter_organization_table_organization_tenant_and_more'),
    ]

    operations = [
        # This migration originally removed Organization.tenant and some legacy
        # models, but those responsibilities were moved to
        # 0004_remove_organization_tenant_alter_incident_options_and_more and
        # later safe migrations. We keep this file as a no-op to preserve the
        # migration history without mutating state twice.
    ]
