# Generated by Django 5.2.11 on 2026-02-18 12:28

import django.db.models.deletion
from django.db import migrations, models, connection


def remove_tenant_field_safe(apps, schema_editor):
    """Safely remove tenant_id column if it exists"""
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'core_organization'
            AND COLUMN_NAME = 'tenant_id'
        """)
        if cursor.fetchone()[0] > 0:
            # Drop foreign key constraints first
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM information_schema.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'core_organization'
                AND COLUMN_NAME = 'tenant_id'
                AND CONSTRAINT_NAME != 'PRIMARY'
            """)
            constraints = cursor.fetchall()
            for constraint in constraints:
                try:
                    cursor.execute(f"ALTER TABLE core_organization DROP FOREIGN KEY `{constraint[0]}`")
                except Exception:
                    pass
            
            # Drop the column
            try:
                cursor.execute("ALTER TABLE core_organization DROP COLUMN tenant_id")
            except Exception:
                pass


def reverse_remove_tenant_field(apps, schema_editor):
    """Reverse operation - no-op"""
    pass


def delete_tenant_table_safe(apps, schema_editor):
    """Safely delete Tenant table if it exists"""
    with connection.cursor() as cursor:
        # Check if table exists (try different possible table names)
        table_names = ['core_tenants', 'core_tenant', 'tenants', 'tenant']
        for table_name in table_names:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.TABLES 
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = %s
            """, (table_name,))
            if cursor.fetchone()[0] > 0:
                try:
                    cursor.execute(f"DROP TABLE IF EXISTS `{table_name}`")
                except Exception:
                    pass


def reverse_delete_tenant_table(apps, schema_editor):
    """Reverse operation - no-op"""
    pass


def create_userprofile_safe(apps, schema_editor):
    """Safely create UserProfile table if it doesn't exist"""
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.TABLES 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'core_userprofile'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if not table_exists:
            # Table doesn't exist, create it using schema_editor
            UserProfile = apps.get_model('core', 'UserProfile')
            schema_editor.create_model(UserProfile)
        # If table exists, do nothing - migration already applied


def reverse_create_userprofile(apps, schema_editor):
    """Reverse operation - drop table if exists"""
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS `core_userprofile`")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_alter_organization_table_organization_tenant_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_tenant_field_safe,
            reverse_remove_tenant_field,
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='operationalupdate',
            options={'managed': False, 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.RunPython(
            create_userprofile_safe,
            reverse_create_userprofile,
        ),
        migrations.RunPython(
            delete_tenant_table_safe,
            reverse_delete_tenant_table,
        ),
    ]
