# Generated by Django 5.2.11 on 2026-02-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenant_alter_organization_table_organization_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='liaison',
            name='countee',
            field=models.CharField(blank=True, help_text='Countee', max_length=100),
        ),
        migrations.AddField(
            model_name='liaison',
            name='dept',
            field=models.CharField(blank=True, help_text='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='liaison',
            name='role',
            field=models.CharField(blank=True, help_text='User role', max_length=100),
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
