# Generated by Django 5.2.11 on 2026-02-19 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_organization_tenant_alter_incident_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=150)),
                ('primary_liaison_name', models.CharField(max_length=100)),
                ('liaison_email', models.CharField(max_length=150)),
                ('key_incident_types', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_communication_channels', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Keep Django's state in sync by removing the legacy tenant
                # relation from Organization. The actual column was dropped
                # safely in
                # 0004_remove_organization_tenant_alter_incident_options_and_more.
                migrations.RemoveField(
                    model_name='organization',
                    name='tenant',
                ),
            ],
            database_operations=[
                # No database operation needed here; tenant_id column was
                # already dropped safely in migration
                # 0004_remove_organization_tenant_alter_incident_options_and_more.
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='liaison',
                    name='countee',
                    field=models.CharField(blank=True, help_text='Countee', max_length=100),
                ),
                migrations.AddField(
                    model_name='liaison',
                    name='dept',
                    field=models.CharField(blank=True, help_text='Department', max_length=100),
                ),
                migrations.AddField(
                    model_name='liaison',
                    name='role',
                    field=models.CharField(blank=True, help_text='User role', max_length=100),
                ),
            ],
            database_operations=[
                # Columns already exist in the legacy database, so we skip
                # issuing ALTER TABLE ADD COLUMN here and only update Django's
                # model state.
            ],
        ),
        migrations.AlterModelTable(
            name='externaluser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='incident',
            table='core_operationalupdate',
        ),
        migrations.AlterModelTable(
            name='operationalupdate',
            table='core_operationalupdate',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='IncidentAssignedUser',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('is_active', models.BooleanField(db_column='is_active', default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                        ('incident_id', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.incident')),
                        ('mapped_user_id', models.ForeignKey(blank=True, db_column='mapped_user_id', help_text='Logged-in user who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                        ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='incident_assignments', to='core.liaison')),
                    ],
                    options={
                        'db_table': 'core_incidents_mapping',
                        'ordering': ['-created_at'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                # The core_incidents_mapping table is already created via raw SQL
                # in code, so we only update Django's model state here.
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='IncidentEvent',
                    fields=[
                        ('log_id', models.AutoField(db_column='log_id', primary_key=True, serialize=False)),
                        ('log_description', models.TextField(db_column='log_description')),
                        ('created_time', models.DateTimeField(auto_now_add=True, db_column='created_time')),
                        ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='core.incident')),
                        ('user_log', models.ForeignKey(blank=True, db_column='user_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_logs_created', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_incident_event',
                        'ordering': ['-created_time'],
                        'managed': True,
                    },
                ),
            ],
            database_operations=[
                # core_incident_event already exists; this keeps Django's state
                # in sync without re-creating the table.
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='UserProfile',
                    fields=[
                        ('user_credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='core.usercredentials')),
                        ('full_name', models.CharField(max_length=255)),
                        ('mobile', models.CharField(blank=True, max_length=20)),
                        ('email', models.EmailField(max_length=254)),
                        ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('operator', 'Operator'), ('analyst', 'Analyst'), ('liaison', 'Liaison'), ('viewer', 'Viewer')], default='viewer', max_length=50)),
                        ('department', models.CharField(blank=True, max_length=255)),
                        ('shift_start_time', models.TimeField(blank=True, help_text='Shift start time (HH:MM format)', null=True)),
                        ('shift_end_time', models.TimeField(blank=True, help_text='Shift end time (HH:MM format)', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('designated_manager', models.ForeignKey(blank=True, help_text='Manager assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.userprofile')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[
                # core_userprofile table may already exist from earlier safe
                # migrations; we only need to sync the Django state here.
            ],
        ),
    ]
