# Generated by Django 5.2.11 on 2026-02-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userstable_remove_organization_tenant_and_more'),
    ]

    operations = [
        # Only update Django's migration graph; Tenant was a legacy model/table
        # already cleaned up earlier, so we don't execute any DB operation here.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Tenant',
                ),
            ],
            database_operations=[
                # No-op at DB level: table/core_tenants already gone.
            ],
        ),
    ]
