# Generated by Django 5.2.11 on 2026-02-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userstable_remove_organization_tenant_and_more'),
    ]

    operations = [
        # Only keep this migration in the graph; Tenant was already removed
        # earlier, so we avoid mutating state again to prevent KeyError when
        # rebuilding the migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # No-op: Tenant model already removed in a prior migration.
            ],
            database_operations=[
                # No-op at DB level: table/core_tenants already gone.
            ],
        ),
    ]
