# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liaison',
            old_name='countee',
            new_name='county',
        ),
    ]
