# Generated by Django 5.2.11 on 2026-03-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_organization_tenant_and_more'),
        ('core', '0006_delete_tenant'),
    ]

    operations = [
    ]
