# Generated by Django 5.2.12 on 2026-03-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_countee_to_county'),
        ('core', '0009_tx_log_system_logs'),
    ]

    operations = [
    ]
