# Generated by Django 5.2.11 on 2026-03-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260306_1117'),
        ('core', '0011_tenant_id_on_new_tables'),
    ]

    operations = [
    ]
