# Generated by Django 5.2.11 on 2026-03-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260312_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=100)),
                ('service_name', models.CharField(db_column='service_name', max_length=255)),
                ('organization_id', models.BigIntegerField(db_column='organization_id')),
                ('tenant_id', models.BigIntegerField(blank=True, db_column='tenant_id', null=True)),
            ],
            options={
                'db_table': 'core_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentCapture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low - Informational'), ('MEDIUM', 'Medium - Potential Impact'), ('HIGH', 'High - Critical Incident'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('impact', models.TextField(blank=True, help_text='Why it matters - operational impact analysis')),
                ('reported_time', models.DateTimeField(db_column='reported_time')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('reported_by', models.CharField(blank=True, db_column='reportedby', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_column='category', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=255, null=True)),
                ('casualties', models.IntegerField(blank=True, db_column='casualties', null=True)),
                ('source', models.CharField(blank=True, db_column='source', max_length=100, null=True)),
                ('tenant_id', models.BigIntegerField(blank=True, db_column='tenant_id', null=True)),
            ],
            options={
                'db_table': 'core_incidents',
                'ordering': ['-reported_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(db_column='shift_id', primary_key=True, serialize=False)),
                ('tenant_id', models.BigIntegerField(db_column='tenant_id')),
                ('shift_type', models.CharField(db_column='shift_type', max_length=20)),
                ('shift_start_time', models.TimeField(db_column='shift_start_time')),
                ('shift_end_time', models.TimeField(db_column='shift_end_time')),
                ('shift_incharge', models.IntegerField(blank=True, db_column='shift_incharge', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
            options={
                'db_table': 'core_shifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituationUpdate',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description')),
                ('update_time', models.DateTimeField(db_column='update_time')),
                ('reported_by', models.CharField(blank=True, db_column='reported_by', max_length=255, null=True)),
                ('department', models.CharField(blank=True, db_column='department', max_length=255, null=True)),
                ('severity_change', models.CharField(blank=True, db_column='severity_change', max_length=50, null=True)),
                ('status_change', models.CharField(blank=True, db_column='status_change', max_length=50, null=True)),
                ('casualties_injured', models.IntegerField(blank=True, db_column='casualties_injured', null=True)),
                ('casualties_dead', models.IntegerField(blank=True, db_column='casualties_dead', null=True)),
                ('affected_area', models.CharField(blank=True, db_column='affected_area', max_length=255, null=True)),
                ('actions_taken', models.TextField(blank=True, db_column='actions_taken', null=True)),
                ('resources_deployed', models.TextField(blank=True, db_column='resources_deployed', null=True)),
                ('next_steps', models.TextField(blank=True, db_column='next_steps', null=True)),
                ('confidence_level', models.CharField(blank=True, db_column='confidence_level', max_length=50, null=True)),
                ('attachments', models.CharField(blank=True, db_column='attachments', max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('tenant_id', models.BigIntegerField(blank=True, db_column='tenant_id', null=True)),
            ],
            options={
                'db_table': 'core_situation_updates',
                'ordering': ['-update_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('tenant_id', models.BigIntegerField(db_column='tenant_id', primary_key=True, serialize=False)),
                ('org_name', models.CharField(db_column='org_name', max_length=255)),
                ('department', models.CharField(blank=True, db_column='department', max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='contact_person', max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
            ],
            options={
                'db_table': 'tenant_domains',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.AlterModelOptions(
            name='incidentassigneduser',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='incidentevent',
            options={'managed': False, 'ordering': ['-created_time']},
        ),
        migrations.RenameIndex(
            model_name='stripepayment',
            new_name='core_stripe_stripe__dbead7_idx',
            old_name='stripepayme_stripe__a97cae_idx',
        ),
        migrations.RenameIndex(
            model_name='stripepayment',
            new_name='core_stripe_status_40c733_idx',
            old_name='stripepayme_status_a932bb_idx',
        ),
        migrations.RenameIndex(
            model_name='stripepayment',
            new_name='core_stripe_user_id_957ef7_idx',
            old_name='stripepayme_user_id_a27b03_idx',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AddField(
            model_name='decision',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='liaison',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant_id',
            field=models.BigAutoField(db_column='tenant_id', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='shiftpacket',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='decision_maker',
            field=models.CharField(blank=True, help_text='Who took the decision, if known (name/role).', max_length=255),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='decision_summary',
            field=models.TextField(blank=True, help_text='AI-identified decision(s) taken in this shift window.'),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='decision_time',
            field=models.DateTimeField(blank=True, help_text='When the decision was taken, if known.', null=True),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='input_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of all inputs (incident + new situation updates + last packet).'),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='what_changed',
            field=models.TextField(blank=True, help_text='AI-generated description of what changed since the last shift packet.'),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='why_it_matters',
            field=models.TextField(blank=True, help_text='AI-generated explanation of why the changes matter operationally.'),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_id',
            field=models.BigIntegerField(blank=True, db_column='tenant_id', null=True),
        ),
        migrations.AlterField(
            model_name='agencyusercounter',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentshiftschedule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liaison',
            name='county',
            field=models.CharField(blank=True, help_text='County', max_length=100),
        ),
        migrations.AlterField(
            model_name='shiftpackethistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shiftpackethistory',
            name='shift',
            field=models.BigIntegerField(blank=True, db_column='shift_id', help_text='Reference to legacy core_shifts.shift_id', null=True),
        ),
        migrations.AlterModelTable(
            name='decision',
            table='core_decision',
        ),
        migrations.AlterModelTable(
            name='externalsubscription',
            table='core_subscriptions',
        ),
        migrations.AlterModelTable(
            name='externaluser',
            table='core_users',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='core_organization',
        ),
        migrations.AlterModelTable(
            name='stripepayment',
            table='core_stripepayments',
        ),
        migrations.AlterModelTable(
            name='userstable',
            table='core_users',
        ),
    ]
