# Generated by Django 5.2.12 on 2026-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shiftpacket_scheduler_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentshiftschedule',
            name='incident_uid',
            field=models.IntegerField(blank=True, db_column='incident_uid', db_index=True, help_text='Shared incident identifier mapped from capture incidents.', null=True),
        ),
        migrations.AddField(
            model_name='shiftpackethistory',
            name='incident_uid',
            field=models.IntegerField(blank=True, db_column='incident_uid', db_index=True, help_text='Shared incident identifier mapped from capture incidents.', null=True),
        ),
        migrations.AlterModelTable(
            name='incidentassigneduser',
            table='core_incident_user_mapping',
        ),
        migrations.AlterModelTable(
            name='incidentevent',
            table='core_incident_events',
        ),
    ]
