# Generated by Django 5.2.12 on 2026-03-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_capture_incident_to_scheduler_log'),
        ('core', '0015_incidentshiftschedule_incident_uid_and_more'),
    ]

    operations = [
    ]
