# Generated by Django 5.2.11 on 2026-03-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agency'),
        ('core', '0016_merge_20260316_1133'),
    ]

    operations = [
    ]
